import { StyleSheet, Dimensions } from "react-native";

const isTablet = Dimensions.get('window').width > 768;

export default StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'space-between',
    minHeight: Dimensions.get('window').height,
  },
  container: {
    paddingHorizontal: isTablet ? 40 : 20,
    paddingTop: 20,
    maxWidth: 600,
    alignSelf: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: isTablet ? 28 : 24,
    fontWeight: 'bold',
    color: '#255736',
    textAlign: 'center',
    backgroundColor:'#FFFFFF',
    fontFamily:'Questrial-Regular',
  },
  imageWrapper: {
    width: '90%',
    height: 200,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'black',
    overflow: 'hidden',
    marginTop: 40,
  },
  imageHeader: {
    width: '100%',
    height: '100%',
  },
  subtitle: {
    fontSize: isTablet ? 18 : 16,
    color: 'black',
    marginBottom: 20,
    textAlign: 'center',
    marginTop: 20,
    fontFamily:'Questrial-Regular',
  },
  form: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginBottom: 30,
    boxShadow: '0px 3px 8px rgba(0,0,0,0.1)',
    elevation: 5,
    width: '95%',
  },
  label: {
    fontWeight: 'bold',
    color: '#255736',
    marginBottom: 10,
    fontSize: 16,
    fontFamily:'Questrial-Regular',
  },
  input: {
    borderColor: '#357447',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#fff',
    textAlignVertical: 'top',
    fontFamily:'Questrial-Regular',
  },
  buttonEnviar: {
    backgroundColor: '#357447',
    paddingVertical: 14,
    borderRadius: 8,
    marginTop: 15,
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
    fontFamily:'Questrial-Regular',
  },
  menuTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#255736',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily:'Questrial-Regular',
  },
  menuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  menuItem: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 10,
    borderColor: '#357447',
    borderWidth: 1,
    padding: 10,
    marginBottom: 15,
    alignItems: 'center',
    boxShadow: '0px 3px 8px rgba(0,0,0,0.1)',
    elevation: 3,
  },
  menuIcon: {
    width: '100%',
    height: 80,
    marginBottom: 10,
    resizeMode: 'contain',
  },
  menuLabel: {
    textAlign: 'center',
    fontWeight: '600',
    color: '#255736',
  },
  footerWrapper: {
    width: '100%',
    backgroundColor: '#357447',
    paddingVertical: isTablet ? 35 : 25,
  },
  footer: {
    paddingHorizontal: 20,
    alignItems: 'center',
    maxWidth: 600,
    alignSelf: 'center',
  },
  footerTitle: {
    fontSize: isTablet ? 20 : 18,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
    fontFamily:'Questrial-Regular',
  },
  footerText: {
    color: 'white',
    textAlign: 'center',
    marginVertical: 5,
    lineHeight: 22,
    fontSize: isTablet ? 16 : 14,
    fontFamily:'Questrial-Regular',
  },
  subscribe: {
    marginTop: 10,
    alignItems: 'center',
    width: '100%',
  },
  subscribeTitle: {
    fontSize: isTablet ? 18 : 16,
    fontWeight: 'bold',
    color: 'white',
    fontFamily:'Questrial-Regular',
  },
  subscribeText: {
    textAlign: 'center',
    marginVertical: 10,
    color: 'white',
    lineHeight: 22,
    fontSize: isTablet ? 15 : 14,
    fontFamily:'Questrial-Regular',
  },
  inputGroup: {
    flexDirection: 'row',
    width: isTablet ? '70%' : '85%',
    maxWidth: 400,
    alignItems: 'center',
  },
  inputSugestao: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'white',
    padding: 10,
    borderRadius: 5,
    flex: 1,
    marginRight: 5,
    marginTop: 15,
    marginBottom: 5,
    height: 35,
    color: 'white',
    fontFamily:'Questrial-Regular',
  },
  inputButton: {
    backgroundColor: '#255736',
    paddingHorizontal: 15,
    justifyContent: 'center',
    borderRadius: 5,
    height: 41,
  },
  inputButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontFamily:'Questrial-Regular',
  },
  socialContainer: {
    flexDirection: 'row',
    marginTop: 2,
    justifyContent: 'center',
  },
  socialIcon: {
    width: 50,
    height: 50,
    marginHorizontal: 0.2,
  },
  footerCopyright: {
    color: 'white',
    fontSize: 12,
    marginTop: 5,
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily:'Questrial-Regular',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
});
