import { StyleSheet } from "react-native";
export default StyleSheet.create({
  background: { flex: 1, width: "100%", height: "100%" },
  container: {
    alignItems: "center",
    backgroundColor: "transparent",
    width: "100%",
    flexGrow: 1,
    justifyContent: "space-between",
  },

  // Navbar
  navbar: {
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: "#357447",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 10,
  },
  navbarLogo: { width: 120, height: 40, resizeMode: "contain" },
  menuContainer: { position: "relative" },
  navbarLinks: { flexDirection: "row", alignItems: "center", gap: 15 },
  navLink: {
    color: "white",
    fontWeight: "bold",
    fontSize: 12,
    fontFamily: "Questrial-Regular",
  },
  dropdownMenu: {
    position: "absolute",
    top: 25,
    right: 0,
    backgroundColor: "white",
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 10,
    zIndex: 1000,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  dropdownItem: {
    paddingVertical: 6,
    fontSize: 14,
    color: "#357447",
    fontWeight: "600",
    width: 140,
  },

  // Card
  card: {
    width: "85%",
    backgroundColor: "#357447",
    borderRadius: 12,
    padding: 20,
    marginVertical: 25,
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  cardImage: { width: "100%", height: 220, borderRadius: 12, marginBottom: 12 },
  cardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "white",
    marginBottom: 10,
    textAlign: "center",
  },
  cardText: {
    textAlign: "justify",
    color: "#e9f6eb",
    lineHeight: 24,
    fontSize: 18,
  },

  // Footer
  footer: {
    alignItems: "center",
    paddingVertical: 15,
    width: "100%",
    backgroundColor: "#357447",
  },
  footerTitle: {
    marginTop: 20,
    fontFamily: "Questrial-Regular",
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
  },
  footerText: {
    fontFamily: "Questrial-Regular",
    textAlign: "center",
    marginVertical: 5,
    color: "white",
  },

  subscribe: { marginTop: 10, alignItems: "center", width: "90%" },
  subscribeTitle: { fontSize: 16, fontWeight: "bold", color: "white" },
  subscribeText: {
    fontFamily: "Questrial-Regular",
    textAlign: "center",
    marginVertical: 10,
    color: "white",
    lineHeight: 20,
  },
  inputGroup: { flexDirection: "row", marginTop: 15, marginBottom: 1, width: "70%" },
  input: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "white",
    padding: 10,
    borderRadius: 5,
    flex: 1,
    marginRight: 5,
    color: "white",
    height: 34,
    fontFamily: "Questrial-Regular",
  },
  inputButton: {
    backgroundColor: "#255736",
    paddingHorizontal: 15,
    justifyContent: "center",
    borderRadius: 5,
  },
  inputButtonText: { color: "white", fontWeight: "bold" },

  socialContainer: { flexDirection: "row", marginTop: 10, justifyContent: "center" },
  socialIcon: { width: 50, height: 40, marginHorizontal: 0.2, borderRadius: 10 },
  footerCopyright: {
    color: "white",
    fontSize: 12,
    textAlign: "center",
    marginTop: 5,
    fontWeight: "bold",
  },
});
