import { StyleSheet } from "react-native";

export default StyleSheet.create({
    background: { flex: 1, width: '100%', height: '100%' },
  scrollContainer: { flexGrow: 1, justifyContent: 'space-between', minHeight: '100%' },
  content: { flex: 1, alignItems: 'center' },

  logoContainer: { alignItems: 'center', marginBottom: 10 },
  logo: { width: 180, height: 180, borderRadius: 15 },

  card: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 4,
    marginBottom: 20,
    marginTop: 40,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    padding: 10,
    marginVertical: 10,
    fontFamily: 'Questrial-Regular',
  },
  linksContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  link: { fontFamily: 'Questrial-Regular', color: '#357447', textDecorationLine: 'underline', fontSize: 12, marginTop: 12 },
  botao: { backgroundColor: '#357447', padding: 15, borderRadius: 6, alignItems: 'center' },
  botaoTexto: { fontFamily: 'Questrial-Regular', color: '#fff', fontWeight: 'bold' },
  voltarBotao: { marginTop: 15, alignItems: 'center' },
  voltarTexto: { fontFamily: 'Questrial-Regular', color: '#357447', fontWeight: 'bold' },

  footer: { marginTop: 80, alignItems: 'center', justifyContent: 'center', paddingVertical: 25, backgroundColor: '#357447', width: '100%' },
  footerTitle: { fontFamily: 'Questrial-Regular', fontSize: 18, fontWeight: 'bold', color: 'white', marginBottom: 5 },
  footerText: { fontFamily: 'Questrial-Regular', color: 'white', textAlign: 'center', marginVertical: 5, lineHeight: 20 },
  subscribe: { marginTop: 10, alignItems: 'center', width: '90%' },
  subscribeTitle: { fontFamily: 'Questrial-Regular', fontSize: 16, fontWeight: 'bold', color: 'white' },
  subscribeText: { fontFamily: 'Questrial-Regular', textAlign: 'center', marginVertical: 10, color: 'white', lineHeight: 20 },
  inputGroup: { flexDirection: 'row', width: '70%', alignItems: 'center' },
  inputSugestao: { backgroundColor: 'transparent', borderWidth: 1, borderColor: 'white', padding: 10, borderRadius: 5, flex: 1, marginRight: 5, height: 34, color: 'white', marginTop: 15, marginBottom: 2, fontFamily: 'Questrial-Regular' },
  inputButton: { backgroundColor: '#255736', paddingHorizontal: 15, justifyContent: 'center', borderRadius: 5, height: 45, width: 41 },
  inputButtonText: { color: 'white', fontWeight: 'bold', paddingRight: 45 },
  socialContainer: { flexDirection: 'row', marginTop: 2, justifyContent: 'center' },
  socialIcon: { width: 50, height: 40, marginHorizontal: 0.2 },
  footerCopyright: { color: 'white', fontSize: 12, textAlign: 'center', marginTop: 5, marginBottom: 5, fontWeight: 'bold', fontFamily: 'Questrial-Regular' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '80%', backgroundColor: 'white', borderRadius: 10, padding: 20, alignItems: 'center' },
  modalTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  modalOption: { backgroundColor: '#357447', width: '100%', padding: 15, borderRadius: 6, marginBottom: 6, alignItems: 'center' },
  modalOptionText: { color: 'white', fontWeight: 'bold', fontSize: 14, fontFamily: 'Questrial-Regular' },
  modalClose: { marginTop: 3 },
  modalCloseText: { color: '#357447', fontWeight: 'bold', fontFamily: 'Questrial-Regular' },

  pickerContainer: { marginTop: 25, width: '100%' },
  pickerLabel: { color: '#357447', fontSize: 14, fontWeight: 'bold', marginBottom: 10 },
  picker: { height: 50, width: '100%', color: '#000' },
});
